apiVersion: 1

providers:
  - name: sockudo
    orgId: 1
    folder: Sockudo
    type: file
    disableDeletion: false
    updateIntervalSeconds: 30
    allowUiUpdates: true
    options:
      path: /etc/grafana/provisioning/dashboards
