use super::*;
use tokio::{io::{AsyncReadExt,AsyncWriteExt},net::{TcpListener,TcpStream}};
pub async fn feedback(){
 use sockudo_push::{domain::*,memory::MemoryPushStore,pipeline::{MemoryPushQueue,PushQueue,PushQueuePayload,PushQueueStage},storage::PushPublishStatusStore,feedback::PushFeedbackProcessor};
 for group in [1,64] {for repeat in 0..5 {
  let store=Arc::new(MemoryPushStore::new());let queue=Arc::new(MemoryPushQueue::new());let count=1024;
  for campaign in 0..count/group {store.put_publish_status(PublishStatus{app_id:"feedback-perf".into(),publish_id:format!("publish-{campaign}"),state:PublishLifecycleState::Dispatching,counters:PublishCounters{planned:group as u64,..Default::default()},fanout_regime:None,retry_after_ms:None,error_reason:None}).await.unwrap();}
  for number in 0..count {let result=DeliveryResult{app_id:"feedback-perf".into(),publish_id:format!("publish-{}",number/group),provider:PushProviderKind::Fcm,batch_id:format!("batch-{number}"),device_id:None,outcome:DeliveryOutcome::Accepted,provider_message_id:Some(format!("provider-{number}")),error:None,attempt:1};queue.produce(PushQueueStage::DeliveryResults,format!("result-{number}"),PushQueuePayload::DeliveryResult(Box::new(result))).await.unwrap();}
  let worker=PushFeedbackProcessor::new(store.clone(),queue.clone());let start=snapshot();let mut delivered=0;while delivered<count{let read=worker.run_once("feedback").await.unwrap();assert!(read>0);delivered+=read;}let elapsed=start.0.elapsed().as_micros();let mut revisions=0;for campaign in 0..count/group{let observed=store.get_versioned_publish_status("feedback-perf",&format!("publish-{campaign}")).await.unwrap().unwrap();assert_eq!(observed.status.counters.succeeded,group as u64);assert_eq!(observed.status.counters.dispatched,group as u64);revisions+=observed.revision-1;}assert_eq!(queue.lag(PushQueueStage::DeliveryResults).await.unwrap().inflight_depth,0);report("P5_feedback",start,json!({"repeat":repeat,"group":group,"delivered":delivered,"processing_us":elapsed,"status_writes":revisions}));
 }}
}
pub async fn limiter(){
 use sockudo_rate_limiter::{RateLimiter,redis_limiter::RedisRateLimiter};use redis::AsyncCommands;
 let direct=redis::Client::open(std::env::var("REDIS_URL").unwrap()).unwrap();let info=direct.get_connection_info().clone();let target=match info.addr(){redis::ConnectionAddr::Tcp(host,port)=>format!("{host}:{port}"),_=>panic!()};
 let listener=TcpListener::bind("127.0.0.1:0").await.unwrap();let addr=listener.local_addr().unwrap();let(dropper,_)=tokio::sync::broadcast::channel::<()>(1);let drop_clone=dropper.clone();let accepted=Arc::new(AtomicUsize::new(0));let connections=accepted.clone();let proxy=tokio::spawn(async move{loop{let(mut incoming,_)=listener.accept().await.unwrap();connections.fetch_add(1,Ordering::SeqCst);let mut upstream=TcpStream::connect(&target).await.unwrap();let mut drop_signal=drop_clone.subscribe();tokio::spawn(async move{tokio::select!{_=tokio::io::copy_bidirectional(&mut incoming,&mut upstream)=>{},_=drop_signal.recv()=>{}}});}});
 let mut conn=direct.get_multiplexed_async_connection().await.unwrap();
 for repeat in 0..5 {let prefix=format!("services-limiter-{}-{repeat}",std::process::id());let key=format!("{prefix}:rl:ip");let client=redis::Client::open(info.clone().set_addr(redis::ConnectionAddr::Tcp(addr.ip().to_string(),addr.port()))).unwrap();let limiter=Arc::new(RedisRateLimiter::new(client,prefix,128,60).await.unwrap());let before=accepted.load(Ordering::SeqCst);dropper.send(()).unwrap();tokio::time::sleep(Duration::from_millis(10)).await;let barrier=Arc::new(tokio::sync::Barrier::new(128));let start=snapshot();let mut tasks=Vec::new();for _ in 0..128{let limiter=limiter.clone();let barrier=barrier.clone();tasks.push(tokio::spawn(async move{barrier.wait().await;limiter.increment("ip").await.unwrap()}));}for task in tasks{assert!(task.await.unwrap().allowed);}let count:usize=conn.zcard(&key).await.unwrap();assert_eq!(count,128);report("S11_reconnect",start,json!({"repeat":repeat,"accepted":count,"new_connections":accepted.load(Ordering::SeqCst)-before}));let _:usize=conn.del(key).await.unwrap();}proxy.abort();
}
async fn server()->(std::net::SocketAddr,Arc<AtomicUsize>,tokio::task::JoinHandle<()>){
 let listener=TcpListener::bind("127.0.0.1:0").await.unwrap();let addr=listener.local_addr().unwrap();let hits=Arc::new(AtomicUsize::new(0));let count=hits.clone();let handle=tokio::spawn(async move{loop{let(mut socket,_)=listener.accept().await.unwrap();let count=count.clone();tokio::spawn(async move{let mut request=Vec::with_capacity(8192);let mut buf=[0u8;4096];loop{let n=socket.read(&mut buf).await.unwrap();if n==0{return;}request.extend_from_slice(&buf[..n]);if let Some(end)=request.windows(4).position(|w|w==b"\r\n\r\n"){let headers=String::from_utf8_lossy(&request[..end]);let body=headers.lines().find_map(|line|line.split_once(':').filter(|(k,_)|k.eq_ignore_ascii_case("content-length")).and_then(|(_,v)|v.trim().parse::<usize>().ok())).unwrap_or(0);if request.len()>=end+4+body{break;}}}let failing=request.starts_with(b"POST /fail ");count.fetch_add(1,Ordering::SeqCst);let response=if failing {b"HTTP/1.1 503 Unavailable\r\nContent-Length: 0\r\nConnection: close\r\n\r\n".as_slice()}else{b"HTTP/1.1 202 Accepted\r\nContent-Length: 0\r\nConnection: close\r\n\r\n".as_slice()};let _=socket.write_all(response).await;});}});(addr,hits,handle)
}
pub async fn lambda(){
 use sockudo_webhook::lambda_sender::LambdaWebhookSender;use sockudo_core::webhook_types::LambdaConfig;
 let(addr,hits,server)=server().await;
 // Process has no other tasks reading environment configuration before this fixture starts.
 unsafe{std::env::set_var("AWS_ENDPOINT_URL_LAMBDA",format!("http://{addr}"));std::env::set_var("AWS_ACCESS_KEY_ID","synthetic");std::env::set_var("AWS_SECRET_ACCESS_KEY","synthetic");std::env::set_var("AWS_EC2_METADATA_DISABLED","true");}
 let sender=LambdaWebhookSender::new();let webhook=Webhook{lambda:Some(LambdaConfig{function_name:"synthetic-function".into(),region:"us-east-1".into()}),..Default::default()};
 for repeat in 0..5 {let before=hits.load(Ordering::SeqCst);let start=snapshot();for _ in 0..32{sender.clone().invoke_lambda(&webhook,"member_added","synthetic",json!({"time_ms":1,"events":[]})).await.unwrap();}assert_eq!(hits.load(Ordering::SeqCst)-before,32);report("S12_clone_invocations",start,json!({"repeat":repeat,"invocations":32}));}server.abort();
}
pub async fn http(){
 use sockudo_webhook::sender::WebhookSender;
 let(addr,hits,server)=server().await;
 for repeat in 0..5 {let apps=Arc::new(MemoryAppManager::new());let mut bad=app("bad");bad.policy.webhooks=Some(vec![Webhook{url:Some(format!("http://{addr}/fail").parse().unwrap()),event_types:vec!["member_added".into()],..Default::default()}]);let mut good=app("good");good.policy.webhooks=Some(vec![Webhook{url:Some(format!("http://{addr}/healthy").parse().unwrap()),event_types:vec!["member_added".into()],..Default::default()}]);apps.create_app(bad).await.unwrap();apps.create_app(good).await.unwrap();let sender=Arc::new(WebhookSender::new(apps,WebhookRetryConfig{enabled:true,max_attempts:Some(2),initial_backoff_ms:500,max_backoff_ms:500,max_elapsed_time_ms:3000},1000));let before=hits.load(Ordering::SeqCst);let mut failing=Vec::new();for _ in 0..20{let sender=sender.clone();failing.push(tokio::spawn(async move{sender.process_webhook_job(job("bad")).await}));}tokio::time::timeout(Duration::from_secs(5),async{while hits.load(Ordering::SeqCst)<before+20{tokio::time::sleep(Duration::from_millis(1)).await;}}).await.unwrap();let start=snapshot();sender.process_webhook_job(job("good")).await.unwrap();report("S13_healthy_during_retry",start,json!({"repeat":repeat,"failed_jobs":20,"healthy":1}));for task in failing{let _=task.await.unwrap();}assert_eq!(hits.load(Ordering::SeqCst)-before,41);}server.abort();
}
